### PR TITLE
Update debian-cd.mdx

### PR DESCRIPTION
**Pull request by ouyen**
Debian CD下载链接好像有一些改变，今天用的时候发现有一点问题，在这里提交一下

### CODE REVIEW

**Comment by ZenithalHourlyRate** [comment]
Check CI

**Comment by ouyen** [comment]
fix

**Comment by taoky** [comment]
Check CI (again)

**Comment by eastonman** [comment]
I wish to merge this PR and then fix the format issue myself.
Is that acceptable @taoky.

**Pull request merged**
